default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: category_development

test:
  <<: *default
  database: category_test
